oslabs-beta/reactime

- src/app/RTKslices.tsx
- src/app/containers/TravelContainer.tsx
> Jimmy feat

- src/app/RTKslices.tsx
- src/app/components/StateRoute/History.tsx
- src/app/components/StateRoute/StateRoute.tsx
also edited what props are received in History
> Finished migrating StateRoute to RTK

- src/app/RTKslices.tsx
- src/app/components/MainSlider.tsx
Travel container components which was main slider was converted to RTK. Logs to RTK Slider also added.
> Travel container components

- src/app/RTKslices.tsx
- src/app/components/Diff.tsx
- src/app/components/Tutorial.tsx
- src/app/containers/ButtonsContainer.tsx
- Migrated Diff.tsx to RTK
- removed the useDispatch and useSelector from inside the class in Tutorial.tsx, opted for prop drilling them down from ButtonsContainer instead
- Fixed the issue in RTKslices where port was being destructured from currentTab instead of state
> Migrated Diff to RTK, fixed hook call and port issue

- src/app/RTKslices.tsx
Clear button functionality works
> clear button on left side works

- src/app/FrontendTypes.ts
- src/app/RTKslices.tsx
- src/app/components/App.tsx
- src/app/components/MainSlider.tsx
- src/app/components/StateRoute/PerformanceVisx/BarGraph.tsx
- src/app/components/StatusDot.tsx
- src/app/components/SwitchApp.tsx
- src/app/components/Tutorial.tsx
- src/app/components/WebMetrics.tsx
- src/app/containers/ActionContainer.tsx
- src/app/containers/ButtonsContainer.tsx
- src/app/containers/ErrorContainer.tsx
- src/app/containers/MainContainer.tsx
- src/app/containers/TravelContainer.tsx
- src/app/index.tsx
- src/app/reducers/mainReducer.js
Merging into previous version, fixed up any old code that was commented out as well as any console.logs that were used for testing.
> Rtk cleanup

- src/app/RTKslices.tsx
- src/app/__tests__/ActionContainer.test.tsx
- src/app/__tests__/action.test.tsx
- src/app/containers/ActionContainer.tsx
- src/app/reducers/mainReducer.js
-changes made to testing suite for action test and action container
> Featurekelvin

- src/app/containers/ButtonsContainer.tsx
- src/app/styles/components/_buttons.scss
- src/app/styles/layout/_buttonsContainer.scss
- src/app/styles/layout/_mainContainer.scss
Finished matching the themes for our reconnect feature.
> UI styling for our pop up reconnect feature complete

- src/app/containers/ButtonsContainer.tsx
- src/app/styles/components/_buttons.scss
- src/app/styles/layout/_buttonsContainer.scss
Added a hazard icon next to the warning header in our pop up window. All the other css needed to be adjusted due to MUI overriding the padding and margins.
> Final pop up style css complete

- src/app/FrontendTypes.ts
- src/app/RTKslices.tsx
- src/app/containers/ButtonsContainer.tsx
- src/app/containers/MainContainer.tsx
- src/extension/background.js
- Solved multiple connection errors and startup errors by making background.js to wait for the frontend to fully render before sending any data
- Added error handlers and retry functionality when trying to connect/reconnect to a port
> Added Error handling for port connections and initialization

- src/app/__tests__/ButtonContainer.test.tsx
- src/app/__tests__/ErrorContainer.test.tsx
- src/app/__tests__/ErrorMsg.test.tsx
- src/app/containers/ButtonsContainer.tsx
button container test file fully converted to use RTK, will clean up commented out code once I know we do not need to review what they did before
> button container test file fully converted to use RTK

- src/app/__tests__/WebMetrics.test.tsx
converted WebMetrics.test.tsx to work with RTK
> converted WebMetrics.test.tsx to work with RTK

- src/app/__tests__/MainContainer.test.tsx
MainContainter Testing file is adjusted to accommodate for Redux Tool Kit.
> MainContainer Test is fixed

- package.json
- src/app/components/StateRoute/StateRoute.tsx
- src/app/styles/layout/_stateContainer.scss
- src/extension/contentScript.ts
We fixed a CSS issue with the web metrics. Added the CLS and INP web metrics to the application. Also fixed a decimal issue with CLS.
> Collaboration for adding our web metrics

- src/app/RTKslices.tsx
- src/app/__tests__/ButtonContainer.test.tsx
- src/app/__tests__/TravelForwardBackward.test.tsx
- src/app/components/StateRoute/History.tsx
- src/app/components/StateRoute/PerformanceVisx/BarGraph.tsx
- src/app/components/StateRoute/PerformanceVisx/PerformanceVisx.tsx
- src/app/components/StateRoute/StateRoute.tsx
- src/app/containers/MainContainer.tsx
- src/app/reducers/mainReducer.js
- src/app/store.tsx
- src/extension/background.js
We are cleaning up any console.logs we left behind and any unnecessary comments we had. We also added some additional comments inside of our main slice file so further groups can iterate on.
> Removed console logs and any outdated comments

- package.json
> removed immer from deps

- src/app/components/StateRoute/History.tsx
- src/app/styles/components/d3graph.css
- src/app/styles/layout/_stateContainer.scss
> Finalbranchkelvin

- jest.config.js
- src/app/FrontendTypes.ts
- src/app/__tests__/ActionContainer.test.tsx
- src/app/__tests__/ButtonContainer.test.tsx
fixed typing/test, ActionContainer.test.tsx
> fixed typing/test, ActionContainer.test.tsx

- src/README.md
Edited Possible Avenues for future iterators.
> Update developer contributor README.MD

- jest.config.js
updated jest config to ignore appropriate files
> updated jest config to ignore appropriate files

- src/app/components/StateRoute/StateRoute.tsx
> Fixed warning showing in Web Metrics when it shouldn't

- README.md
> Readme update for a link to our article

- README.fr.md
> update link to our article

- src/README.md
Added a link to our article for the dev read me
> added link to our article
